// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests SEO optimizations by identifying popular relevant keywords.
 *
 * - suggestSeoOptimizations - A function that handles the SEO optimization suggestion process.
 * - SuggestSeoOptimizationsInput - The input type for the suggestSeoOptimizations function.
 * - SuggestSeoOptimizationsOutput - The return type for the suggestSeoOptimizations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestSeoOptimizationsInputSchema = z.object({
  websiteContent: z
    .string()
    .describe('The content of the website to analyze for SEO optimization.'),
  targetKeywords: z
    .string()
    .describe(
      'A comma-separated list of keywords that the website is targeting.'
    ),
});
export type SuggestSeoOptimizationsInput = z.infer<
  typeof SuggestSeoOptimizationsInputSchema
>;

const SuggestSeoOptimizationsOutputSchema = z.object({
  suggestedKeywords: z
    .array(z.string())
    .describe(
      'A list of suggested keywords to improve SEO, based on the website content and target keywords.'
    ),
  optimizationSuggestions: z
    .string()
    .describe(
      'Suggestions for optimizing the website content based on the suggested keywords.'
    ),
});
export type SuggestSeoOptimizationsOutput = z.infer<
  typeof SuggestSeoOptimizationsOutputSchema
>;

export async function suggestSeoOptimizations(
  input: SuggestSeoOptimizationsInput
): Promise<SuggestSeoOptimizationsOutput> {
  return suggestSeoOptimizationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestSeoOptimizationsPrompt',
  input: {schema: SuggestSeoOptimizationsInputSchema},
  output: {schema: SuggestSeoOptimizationsOutputSchema},
  prompt: `You are an SEO expert. Analyze the website content and target keywords to suggest SEO optimizations.

Website Content: {{{websiteContent}}}
Target Keywords: {{{targetKeywords}}}

Suggest a list of keywords to improve SEO and provide suggestions for optimizing the website content based on the suggested keywords. Return suggestedKeywords as a string array.
Ensure the response is well-formatted and easy to understand, remember to be as concise as possible.
`,
});

const suggestSeoOptimizationsFlow = ai.defineFlow(
  {
    name: 'suggestSeoOptimizationsFlow',
    inputSchema: SuggestSeoOptimizationsInputSchema,
    outputSchema: SuggestSeoOptimizationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
